cups:
  build: .
  restart: always
  volumes:
    - /dev/bus/usb:/dev/bus/usb
    - /var/run/dbus:/var/run/dbus
  ports:
    - 6631:631/tcp
  environment:
    - USERNAME=admin
    - PASSWORD=1234
  privileged: true
        
