version: '2'

networks:
  backend:
    external: 
      name: rpicaddy_backend

services:
  picapport:
    build:
      context: .
      dockerfile: AlpineDockerfile
    restart: always
    expose:
      - 80
    networks:
      - backend
    volumes:
      - ./config:/opt/picapport/.picapport
      - /home/public/NAS/picapport cache:/srv/cache
      - /home/public/NAS/Shared Pictures:/srv/photos

# ocker run -d --name picapport -p 8080:8080 -v $PWD/data/config/:/opt/picapport/.picapport -v /home/public/NAS/Shared\ Pictures:/srv/photos  whatever4711/rpi-picapport
