postgresql:
  image: postgresql
  restart: always
  ports: 
    - 5432:5432
  volumes: 
    - ./postgresql/data:/var/lib/postgresql/data 

phppgadmin:
  image: phppgadmin
  restart: always
  ports:
    - 80:80
  links:
    - postgresql
