version: "2"

networks:
  front:
    driver: bridge

services:
  caddy:
    build: .
    #restart: always
    networks:
      - front
    ports:
      - 80:80
      - 443:443
      - 2015:2015
    volumes:
      - ./site:/srv
      - ./config/Caddyfile:/etc/Caddyfile
    #command: -agree -conf /etc/Caddyfile
