django:
  build: .
  restart: always
  expose:
    - 8000
  volumes:
    -  /home/marcel/scert:/etc/cert
  environment:
    - GRUNT_KEY=/etc/cert/key.pem
    - GRUNT_CERT=/etc/cert/cert.pem
    - DOCKYARD_SRC=/home/marcel/Wedding
#  entrypoint: /bin/bash

haproxy:
  image: hypriot/rpi-haproxy
  restart: always
  ports:
    - 80:80
    - 443:443
    - 8080:8080
  links:
    - django:django
  volumes:
    - ./haproxy:/haproxy-override

