django:
  build: .
  restart: always
  expose:
    - 8000
  environment:
    - DOCKYARD_SRC=/home/marcel/Wedding

haproxy:
  image: hypriot/rpi-haproxy
  restart: always
  ports:
    - 80:80
    - 443:443
    - 8080:8080
  links:
    - django:django
  volumes:
    - ./haproxy:/haproxy-override
    - /home/marcel/scert:/haproxy-override/certs

